// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartActions from "./islands/AddToCartActions.tsx";
import * as $AddToCartButton from "./islands/AddToCartButton.tsx";
import * as $AddToCartLocal from "./islands/AddToCartLocal.tsx";
import * as $BuyWarning from "./islands/BuyWarning.tsx";
import * as $CloseButton from "./islands/CloseButton.tsx";
import * as $CountdownTimer from "./islands/CountdownTimer.tsx";
import * as $Debug from "./islands/Debug.tsx";
import * as $HeaderButton from "./islands/HeaderButton.tsx";
import * as $HeaderModals from "./islands/HeaderModals.tsx";
import * as $HeaderSearchbar from "./islands/HeaderSearchbar.tsx";
import * as $LogComponent from "./islands/LogComponent.tsx";
import * as $NavItem from "./islands/NavItem.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $NewsletterModal from "./islands/NewsletterModal.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductDetailsImages from "./islands/ProductDetailsImages.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $Sort from "./islands/Sort.tsx";
import * as $TopBar from "./islands/TopBar.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartActions.tsx": $AddToCartActions,
    "./islands/AddToCartButton.tsx": $AddToCartButton,
    "./islands/AddToCartLocal.tsx": $AddToCartLocal,
    "./islands/BuyWarning.tsx": $BuyWarning,
    "./islands/CloseButton.tsx": $CloseButton,
    "./islands/CountdownTimer.tsx": $CountdownTimer,
    "./islands/Debug.tsx": $Debug,
    "./islands/HeaderButton.tsx": $HeaderButton,
    "./islands/HeaderModals.tsx": $HeaderModals,
    "./islands/HeaderSearchbar.tsx": $HeaderSearchbar,
    "./islands/LogComponent.tsx": $LogComponent,
    "./islands/NavItem.tsx": $NavItem,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/NewsletterModal.tsx": $NewsletterModal,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductDetailsImages.tsx": $ProductDetailsImages,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/Sort.tsx": $Sort,
    "./islands/TopBar.tsx": $TopBar,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
